In [1]:
import pandas as pd

In [10]:
airport = pd.read_csv('airport.csv')

In [11]:
airport

,country,location,name,code
0,Algeria,Adrar,Touat-Cheikh Sidi Mohamed Belkebir Airport,AZR
1,Algeria,Algiers,Houari Boumedienne Airport,ALG
2,Algeria,Annaba,Rabah Bitat Airport,AAE
3,Algeria,Batna,Batna Airport,BLJ
4,Algeria,Bejaia,Soummam Airport,BJA
...,...,...,...,...
1300,Tuvalu,Funafuti,Funafuti International Airport,FUN
1301,Vanuatu,Luganville,Santo-Pekoa International Airport,SON
1302,Vanuatu,Port Vila,Bauerfield International Airport,VLI
1303,Wallis and Futuna,Futuna,Pointe Vele Airport,FUT
1304,Wallis and Futuna,Wallis,Hihifo Airport,WLS

In [14]:
airport[airport.country== 'Finland']

      country      location                      name code
1186  Finland         Åland         Mariehamn Airport  MHQ
1187  Finland      Helsinki   Helsinki-Vantaa Airport  HEL
1188  Finland       Kittilä           Kittilä Airport  KTT
1189  Finland        Kuopio            Kuopio Airport  KUO
1190  Finland       Kuusamo           Kuusamo Airport  KAO
1191  Finland  Lappeenranta      Lappeenranta Airport  LPP
1192  Finland          Oulu              Oulu Airport  OUL
1193  Finland     Rovaniemi         Rovaniemi Airport  RVN
1194  Finland       Tampere  Tampere-Pirkkala Airport  TMP
1195  Finland         Turku             Turku Airport  TKU
1196  Finland         Vaasa             Vaasa Airport  VAA